# Generated by Django 4.1.7 on 2023-02-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='customer_name',
            new_name='student_name',
        ),
    ]
